---
Name: loveduckie-silverstripe-social-media-tags
---
LoveDuckie\SilverStripe\SocialMetaTags\Extensions\SocialMediaTagsExtension:
  config:
    title:
      default: "Title"
    description:
      default: "Content"
    image:
      default:
    image_width: 1200
    image_height: 627
    description_limit: 300
    description_limit_twitter: 200
    locale: en_GB
    opengraph:
      type:
        default: website
    twitter:
      site: "@YourAliasGoesHere"
      creator: "@YourAliasGoesHere"
      card: summary_large_image
      description_limit: 200
      image_alt_limit: 420
      image_height: 500
      image_width: 958
    social_platforms:
      pinterest:
        image_height: 1200
        image_width: 627
      linkedin:
        image_height: 1200
        image_width: 627
      facebook:
        image_height: 1200
        image_width: 630
      twitter:
        image_height: 800
        image_width: 418
  page_types:
  types:
    SilverStripe\Blog\Model\BlogPost: "article"
